application: laz-alpleri-2013
version: 4
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: staic/index.html

- url: /index\.html
  static_files: static/index.html
  upload: static/index.html

- url: /go/.*
  static_files: static/index.html
  upload: static/index.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
